# Generated by Django 4.2.3 on 2023-07-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_suscriptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscriptor',
            name='apellidoSuscriptor',
            field=models.CharField(default=50, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suscriptor',
            name='direccion',
            field=models.CharField(default=50, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suscriptor',
            name='edad',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suscriptor',
            name='sexo',
            field=models.CharField(default=50, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suscriptor',
            name='tarjeta',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
