# Generated by Django 4.2.3 on 2023-07-28 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_suscriptor_apellidosuscriptor_suscriptor_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscriptor',
            old_name='apellidoSuscriptor',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='suscriptor',
            old_name='nombreSuscriptor',
            new_name='nombre',
        ),
    ]
