# Generated by Django 4.2.3 on 2023-07-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_apellidosuscriptor_suscriptor_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaje',
            name='fechaMuerte',
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='vivo',
        ),
    ]
