# Generated by Django 4.2.3 on 2023-07-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_personaje_fechamuerte_remove_personaje_vivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptor',
            name='apellido',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
