# Generated by Django 4.2.3 on 2023-07-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_suscriptor_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptor',
            name='apellido',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
